import fs from 'node:fs';
import path from 'node:path';
import pc from 'picocolors';
import {
  createEmbeddingProvider,
  type PrecomputedEmbeddingEntry,
  type PrecomputedEmbeddings,
  type EmbeddingProvider,
} from '@edgeroute/core';
import { loadConfig } from '../utils/config-loader.js';

export interface BuildEmbeddingsOptions {
  config?: string;
  output?: string;
  provider?: string;
  model?: string;
  cwd?: string;
}

export async function buildEmbeddingsCommand(options: BuildEmbeddingsOptions): Promise<PrecomputedEmbeddings> {
  const cwd = options.cwd ?? process.cwd();
  console.log(pc.bold(pc.cyan('⚡ EdgeRoute: Building Precompiled Embeddings...')));

  const config = await loadConfig(options.config, cwd);

  if (options.provider) {
    config.embedding = {
      ...config.embedding,
      provider: options.provider as any,
      model: options.model ?? config.embedding?.model,
    };
  }

  const startProvider = performance.now();
  const providerOrPromise = createEmbeddingProvider(config);
  const provider: EmbeddingProvider =
    providerOrPromise instanceof Promise ? await providerOrPromise : providerOrPromise;

  const totalExamples = config.routes.reduce((acc, r) => acc + (r.examples?.length ?? 0), 0);

  if (totalExamples === 0) {
    console.log(pc.yellow('⚠️  No routes with "examples" found in configuration. Nothing to build.'));
  }

  const modelName = (provider as any).modelName ?? config.embedding?.model ?? 'default';

  console.log(
    pc.dim(
      `• Provider: ${pc.bold(provider.name)} | Model: ${pc.bold(modelName)} | Examples: ${totalExamples}`,
    ),
  );

  const startEmbed = performance.now();
  const entries: PrecomputedEmbeddingEntry[] = [];
  let dimensions = 0;

  for (const route of config.routes) {
    if (route.examples && route.examples.length > 0) {
      console.log(
        `  ${pc.cyan('→')} Processing route ${pc.bold(route.name)} (${route.examples.length} examples)...`,
      );
      const vectors = await provider.embedBatch(route.examples);
      for (let i = 0; i < route.examples.length; i++) {
        const text = route.examples[i]!;
        const vector = vectors[i]!;
        if (dimensions === 0 && vector.length > 0) {
          dimensions = vector.length;
        }
        entries.push({
          route: route.name,
          text,
          vector,
        });
      }
    }
  }

  const embedDurationMs = Number((performance.now() - startEmbed).toFixed(2));

  const result: PrecomputedEmbeddings = {
    version: '1.0',
    provider: provider.name,
    model: modelName,
    dimensions: dimensions || 256,
    createdAt: new Date().toISOString(),
    embeddings: entries,
  };

  const outputPath = path.resolve(cwd, options.output ?? 'router.embeddings.json');
  const outputDir = path.dirname(outputPath);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  if (outputPath.endsWith('.ts')) {
    const tsCode = `// Generated by @edgeroute/cli on ${result.createdAt}
// Provider: ${result.provider} | Dimensions: ${result.dimensions}

export const routerEmbeddings = ${JSON.stringify(result, null, 2)} as const;
export default routerEmbeddings;
`;
    fs.writeFileSync(outputPath, tsCode, 'utf-8');
  } else {
    fs.writeFileSync(outputPath, JSON.stringify(result, null, 2), 'utf-8');
  }

  const fileSizeKB = (fs.statSync(outputPath).size / 1024).toFixed(1);

  console.log(pc.green(pc.bold('✔ Offline pre-computation complete!')));
  console.log(`  • Generated:    ${pc.bold(path.relative(cwd, outputPath) || path.basename(outputPath))} (${fileSizeKB} KB)`);
  console.log(`  • Vectors:      ${pc.bold(entries.length.toString())} embeddings (${result.dimensions}-dimensional)`);
  console.log(`  • Compute Time: ${pc.bold(`${embedDurationMs}ms`)}`);
  console.log(pc.dim('  • Edge runtime can now boot with 0ms cold-start vector precomputation overhead.'));
  console.log('');

  return result;
}
